---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  integration:
    name: Run the integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
      - run: |
          pip install --upgrade poetry
      - name: Run tests
        run: |
          poetry install
          poetry run pytest -vv -- -n auto
